version: '3.8'

services:
    mongo:
        image: mongo:6.0.5
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017:27017
        env_file:
            - ./.env
        restart: unless-stopped

    backend:
        build:
            context: ./backend-D7
            dockerfile: dev.Dockerfile
        env_file:
            - ./.env
        volumes:
            - ./backend-D7:/app
        tty: true
        depends_on:
            - mongo

    nginx:
        build: ./nginx/
        restart: unless-stopped
        ports:
            - 80:80
            - 443:443
        depends_on:
            - backend

volumes:
    mongo_data:
